(function(){
document.addEventListener('contextmenu',function(e){e.preventDefault();});
document.addEventListener('selectstart',function(e){e.preventDefault();});
document.addEventListener('copy',function(e){e.preventDefault();});
document.addEventListener('cut',function(e){e.preventDefault();});
document.addEventListener('dragstart',function(e){e.preventDefault();});
document.addEventListener('keydown',function(e){
if(e.key==='F12'){e.preventDefault();}
if(e.ctrlKey&&e.key==='u'){e.preventDefault();}
if(e.ctrlKey&&e.shiftKey&&(e.key==='I'||e.key==='i')){e.preventDefault();}
if(e.ctrlKey&&e.shiftKey&&(e.key==='J'||e.key==='j')){e.preventDefault();}
if(e.ctrlKey&&(e.key==='s'||e.key==='S')){e.preventDefault();}
});
})();
